title: ReactJS Covid Tracker Application Deployment using AWS Services
author: Pranav
email: nadapana1pranav@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The AWS CodePipeline with AWS S3 bucket as source stage, 
  Jenkins server as build stage, 
  AWS CodeDeploy as deployment tool on beta and production stage on AWS Ec2 is the proposed system which makes it easier to rapidly release new features, 
  avoid downtime during application deployment, 
  handle the errors while updating applications and without many risks associated with manual deployments.

# social links
github_username:  Pranav-Nadapana # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
